#+TITLE: chlsdl
#+AUTHOR: usadev1984
#+LANGUAGE: en

a modular program which is extended through modules to save various types of media from various sources. see [[https://github.com/usadev1984/chlsdl-modules/?tab=readme-ov-file#supported-sources][modules repo]] for supported sources.
** dependencies
- [[https://github.com/usadev1984/chlsdl-modules][chlsdl-modules]]
- libxmu
- xclip
- pcre2
- json-c
- libnotify (optional. push notifications)
- pkg-config (build-time only)
** building
*** options
- ~COLOR~: if you want colored output and your terminal has truecolor support, pass ~COLOR=1~ to ~make~ (recommended).
- ~PREFIX~: controls the directory where everything is going to be installed. you most likely don't need to set this variable.
*** building
first, build and install [[https://github.com/usadev1984/chlsdl-modules][chlsdl-modules]].
- build release:
#+BEGIN_SRC shell
  make -j$((`nproc`+1)) release COLOR=1
#+END_SRC
- install with:
#+BEGIN_SRC shell
  sudo make install
#+END_SRC
** usage
1. run the main program with ~chlsdl~
2. navigate to a supported website and press backtick (`) to trigger the js userscript
3. ???
4. profit
** todo
- [ ] fix building on nixos
- [X] add support for sending notifications using libnotify
- [X] move libchlsdl-common to modules repo
